M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu20.04.1} date ma. 11. april 2022 kl. 14.42 +0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-11T14:42:17+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.6Y-0.6
X0.6Y-1.6
X2.6Y-0.6
X2.6Y-1.6
T0
M30
